### ISSUE TITLE
negative yOffset

### ISSUE THREAD

**Issue by Gamer92000** [pitkes22/ts5-channel-image-generator#2]
### Description
Under some circumstances the yOffset can become negative resulting in the first x channels having no banner.

### How To Reproduce
Load an image
Enable `Ignore Spacing`
Slide the channel slider all the way to the right
Set the vertical Offset to 0
Disable `Ignore Spacing`

### Expected Behavior
The vertical Offset is capped to 0 and can not go below

### Actual Behavior
The vertical Offset indicator disappears into negativity and the banner begins only at some channels below the top.

**Comment by pitkes22** [comment]
Another great one :+1:  Thank you :relaxed:
